class template:
    def __init__(self):
        author = [{'name':'ProposalID',
                   'fieldname':'proposalid',
                   'fieldtype':'integer',
                   'section': False},
                  {'name' : 'Number',
                   'fieldname' : 'numb',
                   'fieldtype' : 'integer',
                   'section'   : 'author',
                   'shortname' : '#'},
                  {'name':'Name',
                   'fieldname':'name',
                   'fieldtype':'text',
                   'section':'author'},
                  {'name':'E-mail',
                   'fieldname':'email',
                   'fieldtype':'text',
                   'section':'author'},
                  {'name':'Phone',
                   'fieldname':'phone',
                   'fieldtype':'text',
                   'section':'author'},
                  {'name':'Institution',
                   'fieldname':'institution',
                   'fieldtype':'institution',
                   'section':'author'},
                  {'name':'Thesis',
                   'fieldname':'thesis',
                   'fieldtype':'bool',
                   'section':'author'},
                  {'name':'Graduate Student',
                   'fieldname':'grad',
                   'fieldtype':'bool',
                   'section':'author',
                   'shortname' : 'Grad'}]

        self.author_order = { 1 : 'numb',
                         2 : 'name',
                         3 : 'email',
                         4 : 'phone',
                         5 : 'institution',
                         6 : 'thesis',
                         7 : 'grad' }

        proposal = [{'name':'ProposalID',
                     'fieldname':'proposalid',
                     'fieldtype':'integer',
                     'section': False},
                    {'name':'User',
                     'fieldname':'user',
                     'fieldtype':'text',
                     'section': False},
                    {'name':'Title',
                     'fieldname':'title',
                     'fieldtype':'text',
                     'size':'250',
                     'section':'propinfo'},
                    {'name':'Scientific Category',
                     'fieldname':'scientific_category',
                     'fieldtype':['Cometary', 'Planetary', 'Solar', 'Stellar',
                                  'High-mass Star Formation',
                                  'Low-mass Star Formation', 
                                  'Chemistry / Interstellar Medium',
                                  'Other Galactic', 'Galaxies - Detection', 
                                  'Galaxies - Mapping',
                                  'Cosmology', 'Other Extragalactic'],
                     'section':'propinfo'},
                    {'name':'Date',
                     'fieldname':'date',
                     'fieldtype':'date',
                     'section':'propinfo',
                     'info' : 'YYYY-MM-DD',
                     'line' : 2},
                    {'shortname':'TOO/Time Critical',
                     'name':'Target of Opportunity/Time Critical',
                     'fieldname':'toe',
                     'fieldtype':'bool',
                     'section':'propinfo',
                     'line':2},
                    {'name':'Level of Help Required',
                     'fieldname':'help_required',
                     'fieldtype':['None', 'Consultation',
                                  'Request Collaborator'],
                     'section':'propinfo',
                     'line' : 2},
                    {'name':'1cm Project',
                     'fieldname':'1cm',
                     'fieldtype':'bool',
                     'section':'propinfo',
                     'line':2},
                    {'name':'3mm Project',
                     'fieldname':'3mm',
                     'fieldtype':'bool',
                     'section':'propinfo',
                     'line':2},
                    {'name':'1mm Project',
                     'fieldname':'1mm',
                     'fieldtype':'bool',
                     'section':'propinfo',
                     'line':2},
                    {'name':'Abstract',
                     'fieldname':'abstract',
                     'fieldtype':'longtext',
                     'section':'abstract'},
                    {'name':'Special Requirements',
                     'fieldname':'special_requirements',
                     'fieldtype':'longtext',
                     'section':'special_requirements',
                     'check':[]},]

        fast_modes = [
            'SCI1_3MM_SP_WB',
            'SCI1_3MM_SP_SL',
            'SCI1_3MM_SP_CO',
            'SCI1_3MM_SP_HCO+',
            
            'SCI1_3MM_C23_WB',
            'SCI1_3MM_C23_SL',
            'SCI1_3MM_C23_CO',
            'SCI1_3MM_C23_HCO+',
            
            'SCI1_1MM_SP_WB',
            'SCI1_1MM_SP_SL',
            'SCI1_1MM_SP_CO',
            
            'SCI1_1MM_DP_WB',
            'SCI1_1MM_DP_SL',
            'SCI1_1MM_DP_CO',
            
            'SCI1_1MM_FP_WB',
            'SCI1_1MM_FP_SL',
            'SCI1_1MM_FP_CO',
            
            'SCI2_1CM_SP_WB',
            'SCI2_3MM_SP_WB',
            ]

        source = [
            {
                'name':'ProposalID',
                'fieldname':'proposalid',
                'fieldtype':'integer',
                'section' :False
                },
            {
                'name' : 'Number',
                'shortname':'#',
                'fieldname' : 'numb',
                'fieldtype' : 'integer',
                'section'   : 'source',
                'line'      : 1
                },
            {
                'name':'Source Name',
                'shortname':'Source',
                'fieldname':'f_sourcename',
                'fieldtype':'text',
                'section':'source',
                'line' : 1
                },
            {
                'name':'Right Ascension',
                'shortname':'RA',
                'fieldname':'f_ra',
                'fieldtype':'text',
                'section':'source',
                'line' : 1,
                'info' : 'J2000',
                'check' : ['NoNull', 'NoSpaces', 'raCheck']
                },
            {
                'name':'Declination',
                'shortname':'DEC',
                'fieldname':'f_dec',
                'fieldtype':'text',
                'section':'source',
                'line' : 1,
                'info' : 'J2000',
                'check' : ['NoNull', 'NoSpaces', 'decCheck']
                },
            {
                'name':'LSR Velocity',
                'shortname':'V_LSR',
                'fieldname' : 'f_vlsr',
                'fieldtype' : 'text',
                'section' : 'source',
                'line' : 1,
                #'info' : '',
                #'check' : [],
                },
            {
                'name':'Track Length',
                'shortname':'Length',
                'fieldname' : 'f_time',
                'fieldtype' : 'text',
                'section' : 'source',
                'line' : 1,
                #'info' : '',
                #'check' : [],
                },
            {
                'name':'Correlator Mode',
                'shortname':'Mode',
                'fieldname' : 'f_corrconfig',
                'fieldtype' : fast_modes,
                'section' : 'source',
                'line' : 1,
                #'info' : '',
                #'check' : [],
                },
            {
                'name':'Frequency',
                'shortname':'Freq',
                'fieldname' : 'f_bfreq',
                'fieldtype' : 'text',
                'section' : 'source',
                'line' : 1,
                #'info' : '',
                #'check' : [],
                },
            {
                'name':'Spectral Line Frequency',
                'shortname':'Line Freq',
                'fieldname' : 'f_slfreq',
                'fieldtype' : 'text',
                'section' : 'source',
                'line' : 1,
                #'info' : '',
                #'check' : [],
                },
            {
                'name':'Spectral Line Bandwidth',
                'shortname':'BW',
                'fieldname' : 'f_slbw',
                'fieldtype' : ['62 MHz', '31 MHz', '8 MHz', '2 MHz'],
                'section' : 'source',
                'line' : 1,
                #'info' : '',
                #'check' : [],
                },
            {
                'name':'Mosaic',
                'shortname':'Mosaic',
                'fieldname' : 'f_mosaic',
                'fieldtype' : ['test'],
                'section' : 'source',
                'line' : 1,
                #'info' : '',
                #'check' : [],
                },
            
            ]

        self.source_order = { 
            1 : 'numb',
            2 : 'f_sourcename',
            3 : 'f_ra',
            4 : 'f_dec',
            5 : 'f_vlsr',
            6 : 'f_time',
            7 : 'f_corrconfig',
            8 : 'f_bfreq',
            9 : 'f_slfreq',
            10: 'f_slbw',
            11: 'f_mosaic',
            }
                              
       
        self.sections = [{'section' : 'propinfo',
                          'name'    : 'General Proposal Information',
                          'type'    : 'general',
                          'table'   : 'proposal'},
                         {'section' : 'author',
                          'name'    : 'Authors List',
                          'type'    : 'repeat',
                          'table'   : 'author'},
                         {'section' : 'abstract',
                          'name'    : 'Abstract',
                          'type'    : 'general',
                          'table'   : 'proposal'},
                         {'section' : 'source',
                          'name'    : 'Source Information',
                          'type'    : 'repeat',
                          'table'   : 'source'},
                         {'section' : 'special_requirements',
                          'name'    : 'Special Requirements',
                          'type'    : 'general',
                          'table'   : 'proposal'},]

        self.tables = {'proposal' : { 'value' : proposal,
                                      'type'  : 'single'},
                       'source'   : { 'value' : source,
                                      'type'  : 'repeat'},
                       'author'   : { 'value' : author,
                                      'type'  : 'repeat'}}
