class template:
    def __init__(self):
        author = [{'name':'ProposalID',
                   'fieldname':'proposalid',
                   'fieldtype':'integer',
                   'section': False},
                  {'name' : 'Number',
                   'fieldname' : 'numb',
                   'fieldtype' : 'integer',
                   'section'   : 'author',
                   'shortname' : '#'},
                  {'name':'Name',
                   'fieldname':'name',
                   'fieldtype':'text',
                   'section':'author'},
                  {'name':'E-mail',
                   'fieldname':'email',
                   'fieldtype':'text',
                   'section':'author'},
                  {'name':'Phone',
                   'fieldname':'phone',
                   'fieldtype':'text',
                   'section':'author'},
                  {'name':'Institution',
                   'fieldname':'institution',
                   'fieldtype':'institution',
                   'section':'author'},
                  {'name':'Thesis',
                   'fieldname':'thesis',
                   'fieldtype':'bool',
                   'section':'author'},
                  {'name':'Graduate Student',
                   'fieldname':'grad',
                   'fieldtype':'bool',
                   'section':'author',
                   'shortname' : 'Grad'}]

        proposal = [{'name':'ProposalID',
                     'fieldname':'proposalid',
                     'fieldtype':'integer',
                     'section': False},
                    {'name':'User',
                     'fieldname':'user',
                     'fieldtype':'text',
                     'section': False},
                    {'name':'Title',
                     'fieldname':'title',
                     'fieldtype':'text',
                     'size':'250',
                     'section':'propinfo'},
                    {'name':'Date',
                     'fieldname':'date',
                     'fieldtype':'date',
                     'section':'propinfo',
                     'info' : 'YYYY-MM-DD'},
                    {'shortname':'TOO/Time Critical',
                     'name':'Target of Opportunity/Time Critical',
                     'fieldname':'toe',
                     'fieldtype':'bool',
                     'section':'propinfo'},
                    {'name':'Priority',
                     'fieldname':'priority',
                     'fieldtype':'text',
                     'section':'propinfo',
                     'check':['numeric']},
                    {'name':'Scientific Category',
                     'fieldname':'scientific_category',
                     'fieldtype':['Solar System', 'Galactic', 'Extragalactic'],
                     'section':'propinfo',
                     'line' : 2},
                    {'name':'1cm Project',
                     'fieldname':'1cm',
                     'fieldtype':'bool',
                     'section':'propinfo',
                     'line':2},
                    {'name':'3mm Project',
                     'fieldname':'3mm',
                     'fieldtype':'bool',
                     'section':'propinfo',
                     'line':2},
                    {'name':'1mm Project',
                     'fieldname':'1mm',
                     'fieldtype':'bool',
                     'section':'propinfo',
                     'line':2},
                    {'name':'Level of Help Required',
                     'fieldname':'help_required',
                     'fieldtype':['None', 'Consultation',
                                  'Request Collaborator'],
                     'section':'propinfo',
                     'line' : 2},
                    {'name':'Abstract',
                     'fieldname':'abstract',
                     'fieldtype':'longtext',
                     'section':'abstract'},
                    {'name':'Special Requirements',
                     'fieldname':'special_requirements',
                     'fieldtype':'longtext',
                     'section':'special_requirements',
                     'check':[]},
                    {'name':'Status of Prior CARMA Observations',
                     'fieldname':'prior_obs',
                     'fieldtype':'longtext',
                     'section':'prior_obs',
                     'check':[]},
                    {'name':'Scientific Justification',
                     'fieldname':'scientific_justification',
                     'fieldtype':'longtext',
                     'section':'scientific_justification'},
                    {'name':'Technical Justification',
                     'fieldname':'technical_justification',
                     'fieldtype':'longtext',
                     'section':'technical_justification'}]
         
        source = [{'name':'ProposalID',
                   'fieldname':'proposalid',
                   'fieldtype':'integer',
                   'section' :False},
                  {'name' : 'Number',
                   'shortname':'#',
                   'fieldname' : 'numb',
                   'fieldtype' : 'integer',
                   'section'   : 'source',
                   'line'      : 1},
                  {'name':'Source Name',
                   'shortname':'Source',
                   'fieldname':'name',
                   'fieldtype':'text',
                   'section':'source',
                   'line' : 1},
                  {'name':'Right Ascension',
                   'shortname':'RA',
                   'fieldname':'ra',
                   'fieldtype':'text',
                   'section':'source',
                   'line' : 1,
                   'info' : 'J2000',
                   'check' : ['NoNull', 'NoSpaces', 'raCheck']},
                  {'name':'Declination',
                   'shortname':'DEC',
                   'fieldname':'dec',
                   'fieldtype':'text',
                   'section':'source',
                   'line' : 1,
                   'info' : 'J2000',
                   'check' : ['NoNull', 'NoSpaces', 'decCheck']},
                  {'name':'Frequency of Observation',
                   'shortname':'Freq',
                   'fieldname':'corr_frequency',
                   'fieldtype':'text',
                   'section':'source',
                   'line' : 1,
                   'info' : 'GHz',
                   'check' : ['NoNull', 'Numeric']},
#                  {'name':'A Array Time',
#                   'shortname':'A',
#                   'fieldname':'hrs_a',
#                   'fieldtype':'text',
#                   'section':'source',
#                   'line' : 1,
#                   'info' : 'Hours',
#                   'check' : ['NoNull', 'Numeric']},
#                  {'name':'B Array Time',
#                   'shortname':'B',
#                   'fieldname':'hrs_b',
#                   'fieldtype':'text',
#                   'section':'source',
#                   'line' : 1,
#                   'info' : 'Hours',
#                   'check' : ['NoNull', 'Numeric']},
                  {'name':'C Array Time',
                   'shortname':'C',
                   'fieldname':'hrs_c',
                   'fieldtype':'text',
                   'section':'source',
                   'line' : 1,
                   'info' : 'Hours',
                   'check' : ['NoNull', 'Numeric']},
                  {'name':'D Array Time',
                   'shortname':'D',
                   'fieldname':'hrs_d',
                   'fieldtype':'text',
                   'section':'source',
                   'line' : 1,
                   'info' : 'Hours',
                   'check' : ['NoNull', 'Numeric']},
                  {'name':'E Array Time',
                   'shortname':'E',
                   'fieldname':'hrs_e',
                   'fieldtype':'text',
                   'section':'source',
                   'line' : 1,
                   'info' : 'Hours',
                   'check' : ['NoNull', 'Numeric']},
                  {'name':'SH Array Time',
                   'shortname':'SH',
                   'fieldname':'hrs_sh',
                   'fieldtype':'text',
                   'section':'source',
                   'line' : 1,
                   'info' : 'Hours',
                   'check' : ['NoNull', 'Numeric']},
                  {'name':'Number of Mosaic Fields',
                   'shortname':'# Fields',
                   'fieldname':'numb_fields',
                   'fieldtype':'text',
                   'section':'source',
                   'line' : 1,
                   'check': ['NoNull', 'Integer',
                             'NoZero']},
                  #Begin Correlator Stuff
                  {'name':'Species or Transition Name',
                   'shortname':'Species',
                   'fieldname':'species',
                   'fieldtype':'text',
                   'section':'source',
                   'line' : 1},
                  #Begin Optional A Array Info
                  {'name':'Can Self-Calibrate',
                   'shortname':'Self Cal',
                   'fieldname':'self_cal',
                   'fieldtype':'bool',
                   'section':'source',
                   'line' : 1,
                   'nosummary' : True},
                  {'name':'Imaging/SNR',
                   'shortname':'Imag/SNR',
                   'fieldname':'imaging',
                   'fieldtype':['Imaging', 'SNR'],
                   'section':'source',
                   'line':1 },                   
                  {'name':'Flexible Hour Angle?',
                   'shortname':'Flex.HA',
                   'fieldname':'flexha',
                   'fieldtype':'bool',
                   'section':'source',
                   'line' : 1,
                   'info' : 'Check if yes'}]
       
        self.sections = [{'section' : 'propinfo',
                          'name'    : 'General Proposal Information',
                          'type'    : 'general',
                          'table'   : 'proposal'},
                         {'section' : 'author',
                          'name'    : 'Authors List',
                          'type'    : 'repeat',
                          'table'   : 'author'},
                         {'section' : 'abstract',
                          'name'    : 'Abstract',
                          'type'    : 'general',
                          'table'   : 'proposal'},
                         {'section' : 'source',
                          'name'    : 'Source Information',
                          'type'    : 'repeat',
                          'table'   : 'source'},
                         {'section' : 'special_requirements',
                          'name'    : 'Special Requirements',
                          'type'    : 'general',
                          'table'   : 'proposal'},
                         {'section' : 'prior_obs',
                          'name'    : 'Status of Prior CARMA Observations',
                          'type'    : 'general',
                          'table'   : 'proposal'},
                         {'section' : 'scientific_justification',
                          'name'    : 'Scientific Justification',
                          'type'    : 'general',
                          'table'   : 'proposal'},
                         {'section' : 'technical_justification',
                          'name'    : 'Technical Justification',
                          'type'    : 'general',
                          'table'   : 'proposal'},
                         {'section' : 'image',
                          'name'    : 'Image Attachments',
                          'type'    : 'image',
                          'table'   : None}]

        self.tables = {'proposal' : { 'value' : proposal,
                                      'type'  : 'single'},
                       'source'   : { 'value' : source,
                                      'type'  : 'repeat'},
                       'author'   : { 'value' : author,
                                      'type'  : 'repeat'}}
